### PR TITLE
Add Proportional Snap Icon to src

### PR DESCRIPTION
**Pull request by Spekular**

### CODE REVIEW

**Comment by RebeccaDeField** [comment]
I am in the process of separating each icon into its own .svg, which is a long task so for now it's probably best to add it to the one group .svg so it's not lost?

**Comment by RebeccaDeField** [comment]
If you could commit the single .svg icon in addition, that would make it easier for me to finish organizing the current file I have.

**Comment by Spekular** [comment]
That seems like a good idea to me. What folder/filename system are you
using? (ie what should I name it and which folder do I commit to).

**Comment by RebeccaDeField** [comment]
Folder is named according to icon size, svg is named to match corresponding .png file.

**Comment by Spekular** [comment]
@RebeccaDeField Done!

**Pull request merged**
